---

version: '3.7'
services:
  caddy:
    restart: unless-stopped
    build:
      target: dev_build
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./docker/caddy/certs:/root/.caddy
    ports:
      - "8000:8000"

