---

version: '3.7'
services:
  caddy:
    restart: on-failure
    build:
      target: prod_build
    volumes:
      - type: volume
        source: certs
        target: /root/.caddy
    ports:
      - "80:80"
      - "443:443"

  watchtower:
    container_name: 'watchtower'
    image: v2tec/watchtower:0.2.1
    command: --cleanup --label-enable
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
