---
version: "3.6"
services:

  caddy:
    image: caddy:2.3.0
    restart: always
    env_file: ./docker/.env
    volumes:
      - /home/deploy/wordpress/docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    volumes_from:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - proxynet

  wordpress:
    image: wordpress:fpm
    restart: always
    expose:
      - 9000
    env_file: ./docker/.env
    networks:
      - proxynet
      - webnet
    volumes:
      - wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/iza-slodka
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mysql:5.7
    restart: always
    env_file: ./docker/.env
    networks:
      - webnet
    volumes:
      - db:/var/lib/mysql

networks:
  proxynet:
  webnet:

volumes:
  caddy-config:
  caddy-data:
  db:
  wordpress:
