---
version: "3.6"
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    env_file: ./docker/.env
    volumes:
      - wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/iza-slodka
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mysql:5.7
    restart: always
    env_file: ./docker/.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
