---

version: '3.7'
services:
  caddy:
    restart: unless-stopped
    image:
        "docker.pkg.github.com/damienallen/isa/caddy:master"
    build:
      context: .
      cache_from:
        - "docker.pkg.github.com/damienallen/isa/caddy:master"

volumes:
  certs:
