---

version: "3.7"
services:
  caddy:
    restart: unless-stopped
    image:
        "docker.pkg.github.com/damienallen/isa/caddy:master"
    build:
      target: dev_build
    volumes:
      - ./docker/caddy/certs:/root/.caddy
    ports:
      - "8000:8000"

