---
version: "3.6"
services:

  caddy:
    image: caddy:2.3.0
    restart: always
    env_file: ./docker/.env
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config # configuation autosaves
      - caddy-data:/data # saving certificates
    volumes_from:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - proxynet

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    env_file: ./docker/.env
    networks:
      - proxynet
    volumes:
      - wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/iza-slodka
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mysql:5.7
    restart: always
    env_file: ./docker/.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
