name: Deploy

on:
  push:
    branches:
      - deploy
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build yarn distribution
      run: |
        yarn install
        yarn run build
    - name: Push build files
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: dist
        PUBLISH_DIR: ./dist

    env:
        CI: true
