name: Deploy develop

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build yarn distribution
      run: |
        yarn install
        yarn run build
    - name: Deploy to server
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'dist/'
        dest: 'root@preview.izaslodka.com:/var/www/develop'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"

    env:
        CI: true
