name: Deploy master

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build yarn distribution
      run: |
        yarn install
        yarn run build
    - name: Push build files
      uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: dist
        PUBLISH_DIR: ./dist
    - name: Deploy to server
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'dist/'
        dest: 'root@preview.izaslodka.com:/var/www/master'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"

    env:
        CI: true
